// Palavras e perguntas que as pessoas usam para chegar a cada calculadora (alimentam a busca e o chat).
// Escreva do jeito que o usuário fala: sinônimos, siglas, dúvidas. Toda calculadora precisa de uma linha aqui.
window.TERMOS = {
  'premio-de-preco': 'meu preço está alto ou baixo comparar com concorrentes cobrar mais que o mercado precificação mercado prêmio desconto vs concorrência',
  'concentracao-de-nicho': 'foco nicho segmentos vertical dependência de um segmento diversificar receita por segmento hhi concentração de clientes setor',
  'teste-das-cinco-marcas': 'lembrança de marca awareness share of mind reconhecimento brand posicionamento pesquisa de mercado quem lembra da minha marca',
  'desconto-e-percepcao': 'muito desconto dando desconto negociação cliente pede desconto valor percebido commodity vender por preço',
  'multiplo-de-valor': 'quanto valor o cliente recebe roi do cliente justificar o preço subir o preço preço baseado em valor retorno para o cliente',
  'cac-por-canal': 'qual canal traz cliente mais barato canais de aquisição comparar canais onde investir verba google ads linkedin indicação orgânico custo por canal',
  'funil-trafego': 'anúncios google ads facebook meta cpc cpl cpa roas campanha lucro do tráfego conversão clique lead tráfego pago roas de equilíbrio',
  'pipeline-cobertura': 'meta de vendas pipeline suficiente funil cobre a meta previsão de fechamento oportunidades abertas cobertura de pipeline trimestre',
  'prospeccao-outbound': 'sdr prospecção ativa cold mail cold call e-mails frios reuniões outbound custo por reunião prospecção outbound',
  'roi-saas': 'retorno do tráfego pago vale a pena investir em anúncios quanto custa um cliente novo custo de aquisição cac ltv payback quando o investimento se paga break even coorte roi marketing',
  'forecast-ponderado': 'previsão de vendas forecast probabilidade de fechamento pipeline ponderado quanto vou fechar no mês previsão de receita comercial',
  'impacto-do-desconto': 'vale dar desconto quanto preciso vender a mais desconto compensa promoção black friday oferta cupom',
  'meta-de-vendas': 'quantos leads preciso funil reverso meta de clientes conversão do funil quantas reuniões preciso para bater a meta',
  'precificacao': 'quanto cobrar preço do plano margem desejada markup mensalidade mínima precificar assinatura definir preço',
  'velocidade-de-vendas': 'quanto meu time de vendas gera ciclo de vendas tempo para fechar sales velocity produtividade comercial receita por dia',
  'capacidade-de-entrega': 'backlog prazo de entrega velocidade do time sprint quando vamos entregar fila de demandas capacidade do time desenvolvimento',
  'custo-de-implantacao': 'onboarding implantação ativação do cliente custo de implantar time to value cobrar implantação setup',
  'margem-por-projeto': 'projeto deu lucro software house projeto estourou horas margem do projeto orçamento do projeto valor da hora lucro do projeto',
  'retrabalho-e-escopo': 'retrabalho bugs escopo aberto mudança de escopo horas perdidas desperdício time de desenvolvimento correções escopo fechado',
  'utilizacao-do-time': 'ociosidade horas faturáveis alocação do time utilização capacidade billable time parado horas vendidas',
  'burn-multiple': 'eficiência do burn queimar caixa crescimento custo de crescer investidores burn multiple quanto queimo para crescer',
  'ponto-equilibrio': 'quando empato break even custos fixos quantos clientes para pagar as contas ponto de equilíbrio sair do prejuízo',
  'projecao-mrr': 'projeção de receita recorrente mrr futuro arr crescimento 12 meses quanto vou faturar previsão de mrr',
  'regra-dos-40': 'rule of 40 crescimento e margem eficiência investidores saúde da empresa regra dos 40',
  'runway-e-burn': 'quanto tempo de caixa acaba o dinheiro quando acaba o caixa burn rate runway captação meses de caixa fôlego',
  'churn': 'cancelamentos perda de clientes churn alto retenção base vazando clientes saindo taxa de cancelamento',
  'nps-e-saude': 'nps satisfação do cliente promotores detratores saúde da base clientes insatisfeitos pesquisa de satisfação',
  'nrr-grr': 'retenção de receita net revenue retention expansão base cresce sozinha upsell contração nrr grr retenção líquida',
  'quick-ratio': 'saas quick ratio crescimento contra perdas receita nova contra receita perdida eficiência de crescimento',
  'renovacao-de-contratos': 'renovação contratos vencendo reajuste renovar cliente contratos anuais taxa de renovação',
  'investimento-em-produto': 'novo produto mvp vale investir payback do produto lançar produto custo de desenvolver um produto',
  'priorizacao-rice': 'priorizar roadmap rice qual funcionalidade primeiro backlog de produto priorização ideias',
  'retorno-de-feature': 'nova funcionalidade feature vale construir retorno de funcionalidade roadmap custo de uma feature',
  'servico-vs-produto': 'produtizar transformar serviço em produto horas contra recorrência escala software house virar saas produtização',
  'tamanho-de-mercado': 'tam sam som tamanho do mercado potencial de mercado quantos clientes posso ter mercado endereçável',
  'construir-ou-comprar': 'build vs buy construir ou comprar licença ferramenta desenvolver internamente contratar ferramenta pronta make or buy',
  'custo-de-ia-por-uso': 'custo de ia tokens openai llm gpt claude preço da ia por cliente api modelo de linguagem quanto custa a ia',
  'divida-tecnica': 'dívida técnica manutenção bugs código legado tempo não planejado engenharia refatoração custo da dívida',
  'infra-por-cliente': 'custo de infraestrutura nuvem aws margem bruta custo por cliente servidor hospedagem infra',
  'roi-de-automacao': 'automação agente de ia economizar horas vale automatizar produtividade automatizar processo ia no atendimento',
};
